### ISSUE TITLE
Custom increments for arrows in number entry field

### ISSUE THREAD

**Issue by ruan-xian** [WebAudio-Node-Editor/webaudio-node-editor#24]
Currently, the arrow method of changing the values in a number input field modify the values in increments of 1. This is not really appropriate for many of our fields (for example, gain might be better with something like 0.1, and frequency might be better with something like 50). We should implement a custom control for number entry that allows us to set a custom increment in each place the control is used.

**Comment by hamzamehmood67** [comment]
Can you please assign this to me....? I'm willing to work on this issue

**Comment by ruan-xian** [comment]
> Can you please assign this to me....? I'm willing to work on this issue

Sure, let me know if you need any help/documentation

**Comment by hamzamehmood67** [comment]
Thank. I'm excited to get started, but I could use some guidance on where to begin and where I can find the relevant documentation. Could you please point me in the right direction?
