### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by ruan-xian** [WebAudio-Node-Editor/webaudio-node-editor#31]
Now that we're adding more elements to the UI (for example, comments and undo/redo) we should intentionally design the look and layout of our features.

Some things to consider:
1. Should we reposition buttons into different logical groups/locations?
2. Should comments stay like they are in the dropdown, or should we move comment creation into the context menu with the rest of the nodes?
3. Minor style details - color/overall appearance of comment nodes, hover color of undo/redo (also we can consider greying out undo/redo when they aren't valid)

We'll likely have to redesign every once in a while as we continue adding features but it's worth thinking about!

**Comment by akrishna-swe** [comment]
[Figma Designs for Documentation Page](https://www.figma.com/file/JLwp5W7pTtY2TOKkzhoVzM/UI-Improvements?type=design&node-id=11%3A4&mode=design&t=5Y1I5JwsajJbt5AX-1)
