### ISSUE TITLE
Comment save/load

### ISSUE THREAD

**Issue by ruan-xian** [WebAudio-Node-Editor/webaudio-node-editor#33]
Comments don't currently get stored or loaded in import/export - this seems like a Rete issue! We might be able to fix this by extending the comment class and making our own custom versions of comments.

**Comment by ruan-xian** [comment]
See [this documentation](https://retejs.org/docs/guides/import-export) for how saving and loading works

**Comment by santolucito** [comment]
closing this since comments probably need to be reworked anyway
