### ISSUE TITLE
Add chat box with OpenAI API call

### ISSUE THREAD

**Issue by awissink** [WebAudio-Node-Editor/webaudio-node-editor#36]
Parent issue #19; creating the chat box with an interface allowing a user to interact with GPT and making the subsequent API call

**Comment by awissink** [comment]
Parent issue #19

**Comment by santolucito** [comment]
should we merge this into main? seemed like the demo was solid enough

**Comment by ac4982** [comment]
Sure, if you feel like it was solid enough then for sure! Though there were
some cases that did not produce any output, but nothing that’ll break the
website

**Comment by santolucito** [comment]
ok ill let @ruan-xian handle the merge then.

**Comment by santolucito** [comment]
Maybe the next step we need is @awissink or someone to make a pull request?

**Comment by ruan-xian** [comment]
I merged already - sorry for the confusion! The chat box is live on the deployed version.
